### ISSUE TITLE
Not recognizing fill/color aes

### ISSUE THREAD

**Issue by oushujun** [NicolasH2/ggbrace#3]
Hi @Solatar 

Thanks for the package! I encounter errors when trying to use it on slightly complex plots with fill/color options. For example:

>test = ggplot(mtcars, aes(cyl, mpg, fill = factor(vs))) + geom_bar(stat='identity', position = 'dodge')   
test + geom_brace(ystart=-5, pointing="side")
Error in factor(vs) : object 'vs' not found

Any ideas to work around this? 

Best,
Shujun

**Comment by NicolasH2** [comment]
Thanks a lot for your feedback. I just fixed this error. It should not come up again.
The function was lacking a inherit.aes=FALSE argument.

Let me know if the error keeps showing up if you install the package again.

**Comment by oushujun** [comment]
Thanks for the quick response. I was trying to reinstall it but the problem remains. I am not sure if my approach is correct:

>devtools::install_github("NicolasH2/ggbrace@main", force=T)

Does this approach require releasing a new version? My R says the installed version is 0.1.0 which was released a while ago.

Thank you for your help!

**Comment by NicolasH2** [comment]
that is weird, but maybe you are right, and I should have to release a new version.
I think you can circumvent the problem by deinstalling the package and then reinstalling it again

`remove.packages("ggbrace")`
`devtools::install_github("nicolash2/ggbrace")`

**Comment by oushujun** [comment]
I removed it and have it reinstalled, still not working. However, when I restart RStudio or open up a new window, it works! I don't know why it requires restarting but it's working well now.

For what is worth mentioning, I am using macOS High Sierra, R version 4.0.3, and RStudio version 1.1.442.

Thanks for this nice package!

Best,
Shujun

**Comment by NicolasH2** [comment]
Glad to hear it worked out in the end.
Thanks for the link, seems extremely useful.
